### ISSUE TITLE
Setting up with Google Cloud Functions

### ISSUE THREAD

**Issue by kevin-kretz** [arcreative/xbox-on#12]
I am trying to set this program up with Google Cloud Functions in order to make this work with the Google Assistant and therefore my Google Home Mini.  I tried copying the index.js file to the function and also the .json file to its respective spot, but it says it is unable to deploy.
-Is it because I didn't include the cli.js file?
-Did I miss a part of the code where I was supposed to insert my ip address and live device id?
-Did I do something wrong with the "function to execute" section at the bottom?

Any help would be greatly appreciated!
![screenshot](https://user-images.githubusercontent.com/6283412/50530896-a2ed4200-0abf-11e9-9a04-0a5541bc9005.png)

**Comment by arcreative** [comment]
I'm not sure, but I feel like the documentation is pretty complete... The usual setup would be to install the node module and instantiate the module, but it looks like you might be doing something different.  You also need to make sure that whatever's executing this code has access to your local network.

**Comment by Fredde87** [comment]
Never used Google Cloud Functions but the program comes as a module and normally requires npm to be installed as it is. Guessing Google Cloud Functions does not have this so you'll need to modify it to work.

Assuming Google has full node.js support then all you should need is the index file you have and at the bottom add the following,

```
var xbox = new Xbox("192.168.0.128", "FD006CE51AA0E3FD"); // Create new xbox

// Optional, defaults shown
var options = {
    tries: 5,
    delay: 1000,
    waitForCallback: false
};

xbox.powerOn(options);
```

Replace obviously with your own Xbox's IP and its LiveID. Remember you'll need to setup port forwarding for this to work since you are connecting into your home network from the internet. So make sure you enter your public IP and not a private internal IP.
